// Code generated by "goconfig -type flag.ErrorHandling,CommandName|string -option -output config_generated.go -configOption Option"; DO NOT EDIT.

package fcli

import "flag"

type ConfigItem[T any] struct {
	modified     bool
	value        T
	defaultValue T
}

func (s *ConfigItem[T]) Set(value T) {
	s.modified = true
	s.value = value
}
func (s *ConfigItem[T]) Get() T {
	if s.modified {
		return s.value
	}
	return s.defaultValue
}
func (s *ConfigItem[T]) Default() T {
	return s.defaultValue
}
func (s *ConfigItem[T]) IsModified() bool {
	return s.modified
}
func NewConfigItem[T any](defaultValue T) *ConfigItem[T] {
	return &ConfigItem[T]{
		defaultValue: defaultValue,
	}
}

type Config struct {
	ErrorHandling *ConfigItem[flag.ErrorHandling]
	CommandName   *ConfigItem[string]
}
type ConfigBuilder struct {
	errorHandling flag.ErrorHandling
	commandName   string
}

func (s *ConfigBuilder) ErrorHandling(v flag.ErrorHandling) *ConfigBuilder {
	s.errorHandling = v
	return s
}
func (s *ConfigBuilder) CommandName(v string) *ConfigBuilder {
	s.commandName = v
	return s
}
func (s *ConfigBuilder) Build() *Config {
	return &Config{
		ErrorHandling: NewConfigItem(s.errorHandling),
		CommandName:   NewConfigItem(s.commandName),
	}
}

func NewConfigBuilder() *ConfigBuilder { return &ConfigBuilder{} }
func (s *Config) Apply(opt ...Option) {
	for _, x := range opt {
		x(s)
	}
}

type Option func(*Config)

func WithErrorHandling(v flag.ErrorHandling) Option {
	return func(c *Config) {
		c.ErrorHandling.Set(v)
	}
}
func WithCommandName(v string) Option {
	return func(c *Config) {
		c.CommandName.Set(v)
	}
}
